#!/usr/bin/env bash
# deploy-testnet.sh — Full testnet deployment script
# Run from the repo root: bash scripts/deploy-testnet.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
CONTRACTS_DIR="$ROOT/contracts"
PACKAGES_DIR="$ROOT/packages"
OUTPUT_FILE="$SCRIPT_DIR/deployed-contracts.json"

# ── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

echo -e "\n${BLUE}🌟 Family Allowance Manager — Testnet Deployment${NC}"
echo "═══════════════════════════════════════════════════════"

# ── Prerequisites ────────────────────────────────────────────────────────────
command -v stellar >/dev/null 2>&1 || { echo -e "${RED}❌ stellar CLI not found. Install: cargo install --locked stellar-cli --features opt${NC}"; exit 1; }
command -v node >/dev/null 2>&1    || { echo -e "${RED}❌ node not found${NC}"; exit 1; }

# ── Step 1: Create & fund deployer ───────────────────────────────────────────
echo -e "\n${YELLOW}Step 1: Create deployer account${NC}"
stellar keys generate --fund deployer --network testnet 2>/dev/null || echo "  ℹ️  Account already exists"
ADMIN=$(stellar keys address deployer)
echo -e "  ${GREEN}✅ Admin address: $ADMIN${NC}"

# ── Step 2: Build contracts ───────────────────────────────────────────────────
echo -e "\n${YELLOW}Step 2: Build Soroban contracts${NC}"
cd "$CONTRACTS_DIR"
stellar contract build
echo -e "  ${GREEN}✅ Contracts built${NC}"

# ── Step 3: Deploy family_registry ───────────────────────────────────────────
echo -e "\n${YELLOW}Step 3: Deploy family_registry${NC}"
REGISTRY_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/family_registry.wasm \
  --source deployer \
  --network testnet \
  --ignore-checks 2>/dev/null | tail -1)
echo -e "  ${GREEN}✅ family_registry: $REGISTRY_ID${NC}"

# ── Step 4: Initialize family_registry ───────────────────────────────────────
echo -e "\n${YELLOW}Step 4: Initialize family_registry${NC}"
stellar contract invoke \
  --id "$REGISTRY_ID" \
  --source deployer \
  --network testnet \
  -- initialize --admin "$ADMIN"
echo -e "  ${GREEN}✅ Initialized${NC}"

# ── Step 5: Get XLM SAC ───────────────────────────────────────────────────────
echo -e "\n${YELLOW}Step 5: Get XLM SAC contract ID${NC}"
XLM_SAC_ID=$(stellar contract id asset --asset native --network testnet)
echo -e "  ${GREEN}✅ XLM SAC: $XLM_SAC_ID${NC}"

# ── Step 6: Deploy allowance_distributor ──────────────────────────────────────
echo -e "\n${YELLOW}Step 6: Deploy allowance_distributor${NC}"
DISTRIBUTOR_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/allowance_distributor.wasm \
  --source deployer \
  --network testnet \
  --ignore-checks 2>/dev/null | tail -1)
echo -e "  ${GREEN}✅ allowance_distributor: $DISTRIBUTOR_ID${NC}"

# ── Step 7: Initialize allowance_distributor ──────────────────────────────────
echo -e "\n${YELLOW}Step 7: Initialize allowance_distributor${NC}"
stellar contract invoke \
  --id "$DISTRIBUTOR_ID" \
  --source deployer \
  --network testnet \
  -- initialize \
  --admin "$ADMIN" \
  --registry_contract "$REGISTRY_ID" \
  --token_contract "$XLM_SAC_ID"
echo -e "  ${GREEN}✅ Initialized${NC}"

# ── Step 8: Generate TypeScript bindings ──────────────────────────────────────
echo -e "\n${YELLOW}Step 8: Generate TypeScript bindings${NC}"
cd "$ROOT"

stellar contract bindings typescript \
  --contract-id "$REGISTRY_ID" \
  --output-dir "$PACKAGES_DIR/family_registry" \
  --network testnet \
  --overwrite
(cd "$PACKAGES_DIR/family_registry" && npm install && npm run build)
echo -e "  ${GREEN}✅ family_registry bindings generated${NC}"

stellar contract bindings typescript \
  --contract-id "$DISTRIBUTOR_ID" \
  --output-dir "$PACKAGES_DIR/allowance_distributor" \
  --network testnet \
  --overwrite
(cd "$PACKAGES_DIR/allowance_distributor" && npm install && npm run build)
echo -e "  ${GREEN}✅ allowance_distributor bindings generated${NC}"

# ── Step 9: Write frontend env file ───────────────────────────────────────────
echo -e "\n${YELLOW}Step 9: Writing frontend/.env.local${NC}"
cat > "$ROOT/frontend/.env.local" << EOF
# Auto-generated by deploy-testnet.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
NEXT_PUBLIC_STELLAR_NETWORK=testnet
NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
NEXT_PUBLIC_SOROBAN_RPC_URL=https://soroban-testnet.stellar.org
NEXT_PUBLIC_HORIZON_URL=https://horizon-testnet.stellar.org
NEXT_PUBLIC_FAMILY_REGISTRY_CONTRACT_ID=$REGISTRY_ID
NEXT_PUBLIC_ALLOWANCE_DISTRIBUTOR_CONTRACT_ID=$DISTRIBUTOR_ID
NEXT_PUBLIC_XLM_SAC_CONTRACT_ID=$XLM_SAC_ID
NEXT_PUBLIC_STELLAR_EXPLORER_URL=https://stellar.expert/explorer/testnet
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_ENABLE_ACTIVITY_FEED=true
NEXT_PUBLIC_ACTIVITY_POLL_INTERVAL_MS=5000
NEXT_PUBLIC_ENABLE_ANALYTICS=true
NEXT_PUBLIC_ENABLE_SAVINGS_GOALS=true
LOG_LEVEL=info
EOF

# ── Step 10: Save deployed addresses JSON ─────────────────────────────────────
cat > "$OUTPUT_FILE" << EOF
{
  "network": "testnet",
  "deployedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "admin": "$ADMIN",
  "contracts": {
    "family_registry": "$REGISTRY_ID",
    "allowance_distributor": "$DISTRIBUTOR_ID",
    "xlm_sac": "$XLM_SAC_ID"
  },
  "explorer": {
    "family_registry": "https://stellar.expert/explorer/testnet/contract/$REGISTRY_ID",
    "allowance_distributor": "https://stellar.expert/explorer/testnet/contract/$DISTRIBUTOR_ID"
  }
}
EOF

# ── Summary ────────────────────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════"
echo -e "${GREEN}🎉 Testnet deployment complete!${NC}"
echo "═══════════════════════════════════════════════════════"
echo -e "  family_registry:       ${BLUE}$REGISTRY_ID${NC}"
echo -e "  allowance_distributor: ${BLUE}$DISTRIBUTOR_ID${NC}"
echo -e "  XLM SAC:               ${BLUE}$XLM_SAC_ID${NC}"
echo ""
echo -e "📋 ${YELLOW}Next steps:${NC}"
echo "  1. Update README.md Contract Addresses section with the above IDs"
echo "  2. cd frontend && npm run dev"
echo "  3. Paste contract IDs into README.md placeholders"
echo "  4. Deployed addresses saved to: $OUTPUT_FILE"
echo "═══════════════════════════════════════════════════════"
